move:
  ros__parameters:
    plugins:
      - house_move_bt_node
    waypoints: ["salon", "pasillo", "cocina", "h1", "h2", "b1", "b2", "z1", "z2", "z3", "z4", "z5"]
    waypoint_coords:
      salon: [0.44, 1.41, 0.0]
      pasillo: [-2.11, -1.02, 0.0]
      cocina: [1.57, -2.40, 0.0]
      h1: [-3.66, 1.25, 0.0]
      h2: [-4.08, -3.96, 0.0]
      b1: [-4.41, -0.54, 0.0]
      b2: [-1.67, 2.66, 0.0]
      z1: [3.41, -0.58, 0.0]
      z2: [2.80, 3.88, 0.0]
      z3: [3.75, -4.78, 0.0]
      z4: [3.99, -2.92, 0.0]
      z5: [-6.20, 1.34, 0.0]
move_to_zone:
  ros__parameters:
    plugins:
      - house_move_bt_node
    waypoints: ["salon", "pasillo", "cocina", "h1", "h2", "b1", "b2", "z1", "z2", "z3", "z4", "z5"]
    waypoint_coords:
      salon: [0.44, 1.41, 0.0]
      pasillo: [-2.11, -1.02, 0.0]
      cocina: [1.57, -2.40, 0.0]
      h1: [-3.66, 1.25, 0.0]
      h2: [-4.08, -3.96, 0.0]
      b1: [-4.41, -0.54, 0.0]
      b2: [-1.67, 2.66, 0.0]
      z1: [3.41, -0.58, 0.0]
      z2: [2.80, 3.88, 0.0]
      z3: [3.75, -4.78, 0.0]
      z4: [3.99, -2.92, 0.0]
      z5: [-6.20, 1.34, 0.0]
move_out_zone:
  ros__parameters:
    plugins:
      - house_move_bt_node
    waypoints: ["salon", "pasillo", "cocina", "h1", "h2", "b1", "b2", "z1", "z2", "z3", "z4", "z5"]
    waypoint_coords:
      salon: [0.44, 1.41, 0.0]
      pasillo: [-2.11, -1.02, 0.0]
      cocina: [1.57, -2.40, 0.0]
      h1: [-3.66, 1.25, 0.0]
      h2: [-4.08, -3.96, 0.0]
      b1: [-4.41, -0.54, 0.0]
      b2: [-1.67, 2.66, 0.0]
      z1: [3.41, -0.58, 0.0]
      z2: [2.80, 3.88, 0.0]
      z3: [3.75, -4.78, 0.0]
      z4: [3.99, -2.92, 0.0]
      z5: [-6.20, 1.34, 0.0]
pick:
  ros__parameters:
    plugins:
      - house_pick_bt_node
drop:
  ros__parameters:
    plugins:
      - house_drop_bt_node
